proc means data = Acivil;
var Award2;
run;
proc freq data = Acivil ;
table Award2*race /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2 * sex /chisq norow noPercent;
run;
proc corr data = Acivil spearman;
var YearExonerated;
with Award2;
run;
proc corr data = Acivil spearman;
var yearslost;
with Award2;
run;
proc freq data = Acivil ;
table Award2*GuiltyP /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*IO /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*crime /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*DNA /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*Death /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*FC /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*MWID /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*FMFE /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*PFA /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*OM /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*ILD /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*Area /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*RB /chisq norow noPercent;
run;
proc freq data = Acivil ;
table Award2*CIU /chisq norow noPercent;
run;
