proc means data = civil;
var CFiled;
run;
proc freq data = civil ;
table CFiled*race /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled * sex /chisq norow noPercent;
run;
proc corr data = civil spearman;
var YearExonerated;
with CFiled;
run;
proc corr data = civil spearman;
var yearslost;
with CFiled;
run;
proc freq data = civil ;
table CFiled*GuiltyP /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*IO /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*crime /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*DNA /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*Death /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*FC /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*MWID /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*FMFE /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*PFA /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*OM /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*ILD /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*Area /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*RB /chisq norow noPercent;
run;
proc freq data = civil ;
table CFiled*CIU /chisq norow noPercent;
run;
