proc means data = state;
var StateClaimMade;
run;
proc freq data = state ;
table StateClaimMade*race /chisq norow noPercent;
run;
proc freq data = state ;
table StateClaimMade * sex /chisq norow noPercent;
run;
proc corr data = state spearman;
var YearExonerated;
with StateClaimMade;
run;
proc corr data = state spearman;
var yearslost;
with StateClaimMade;
run;
proc freq data = state ;
table StateClaimMade*GuiltyP /chisq norow noPercent;
run;
proc freq data = state ;
table StateClaimMade*IO /chisq norow noPercent;
run;
proc freq data = state ;
table StateClaimMade*crime /chisq norow noPercent;
run;
proc freq data = state ;
table StateClaimMade*DNA /chisq norow noPercent;
run;
proc freq data = state ;
table StateClaimMade*Death /chisq norow noPercent;
run;
proc freq data = state ;
table StateClaimMade*FC /chisq norow noPercent;
run;
proc freq data = state ;
table StateClaimMade*MWID /chisq norow noPercent;
run;
proc freq data = state ;
table StateClaimMade*FMFE /chisq norow noPercent;
run;
proc freq data = state ;
table StateClaimMade*PFA /chisq norow noPercent;
run;
proc freq data = state ;
table StateClaimMade*OM /chisq norow noPercent;
run;
proc freq data = state ;
table StateClaimMade*ILD /chisq norow noPercent;
run;
